name: Frontend Deploy
run-name: Deployend frontend changes push from ${{ github.actor }}
on: [push]
jobs:
  Frontend-Deploy:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:  
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: npm install
        working-directory: ./frontend
        run: npm install
      - name: npm run build
        working-directory: ./frontend
        run: npm run build
      - name: OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::639886339024:role/github-actions-marciogh.com
      - name: S3 rm
        run: aws s3 rm --recursive s3://marciogh.com/app/
      - name: S3 upload
        working-directory: ./frontend
        run: aws s3 cp ./build s3://marciogh.com/app/ --recursive
